Repository inertiajs/inertia, pull requests merged in 2021-12, with the labels that each got.

#533 Change qs.stringify arrayFormat to indices
  packages/inertia/src/url.ts
Labels: todo, investigate

#994 Query String: Allow different 'Array' formatters
  packages/inertia-react/src/Link.js
  packages/inertia-svelte/src/link.js
  packages/inertia-vue/src/link.js
  packages/inertia-vue/tests/app/Pages/Links/Data/Object.vue
  packages/inertia-vue/tests/app/Pages/Visits/Data/Object.vue
  packages/inertia-vue/tests/cypress/integration/links.test.js
  packages/inertia-vue/tests/cypress/integration/manual-visits.test.js
  packages/inertia-vue3/src/link.js
  packages/inertia/src/router.ts
  packages/inertia/src/types.ts
  packages/inertia/src/url.ts
Labels: enhancement, vue 2, react, svelte, core, vue 3

#944 Expose "setErrors" method in useForm
  packages/inertia-react/src/useForm.js
Labels: enhancement, todo
